ALTER TYPE "PlexShelfType" ADD VALUE IF NOT EXISTS 'FAMILY_POPULAR';
ALTER TYPE "PlexShelfType" ADD VALUE IF NOT EXISTS 'GENRE';
ALTER TYPE "PlexShelfType" ADD VALUE IF NOT EXISTS 'DECADE';

ALTER TABLE "PlexCollection" ADD COLUMN IF NOT EXISTS "shelfConfig" JSONB;